/*
*
*   Ficha 2
*   TPSI
*   Pedro dos Santos Alves
*
*/

/*
*
*   16 de Março de 2018
*
*/

/* Ex 1 #1 */
SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS') AS "Hora Atual" FROM DUAL;

/* Ex 2 #1 */
SELECT TRIM(TO_CHAR(SYSDATE, 'Day, ddth "de" Month')) || TO_CHAR(SYSDATE, ' YYYY') AS "Data Atual" FROM DUAL;

/* Ex 3 #1 */
SELECT TRIM(TO_CHAR(TO_DATE('01-01-2000', 'dd-mm-yyyy'), 'Day')) AS "Dia da Semana" FROM DUAL;

/* Ex 4 #16 */
SELECT TITULO, PRECO_TABELA AS "Preço de Tabela" FROM LIVROS WHERE DATA_EDICAO > SYSDATE - 3000;

/* Ex 5 #2 Modificado */
SELECT TITULO FROM LIVROS WHERE DATA_EDICAO BETWEEN TO_DATE('01-01-2002', 'DD-MM-YYYY') AND TO_DATE('31-12-2002', 'DD-MM-YYYY');

-- Simplificado
SELECT TITULO FROM LIVROS WHERE TO_CHAR(DATA_EDICAO, 'yyyy') = 2002;

/* Ex 6 #21 */
SELECT NOME AS "Nome Completo", SUBSTR(NOME, 1, 5) AS "5 Letras do Nome" FROM AUTORES;

/* Ex 7 #21 */
SELECT NOME AS "Nome Completo", SUBSTR(NOME, 1, INSTR(NOME, ' ') - 1) AS "Primeiro Nome" FROM AUTORES;

/* Ex 8 #21 */
SELECT NOME AS "Nome Completo", SUBSTR(NOME, 1, INSTR(NOME, ' ') - 1) AS "Primeiro Nome", SUBSTR(NOME, INSTR(NOME, ' ', -1) + 1) AS "Ultimo Nome" FROM AUTORES;

/*
*
*   23 de Março de 2018
*
*/

/* Ex 9 #21 */
SELECT RPAD(NOME, 22, ' ') AS "Nome Completo", LPAD(NOME, 22, ' ') AS "Nome Alinhado"
FROM AUTORES;

/* Ex 10 #3 */
SELECT TITULO
FROM LIVROS, AUTORES
WHERE SUBSTR(AUTORES.NOME, INSTR(AUTORES.NOME, ' ', -1) + 1) = 'Loureiro' AND AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR;

-- Simplificado
SELECT TITULO
FROM LIVROS, AUTORES
WHERE AUTORES.NOME LIKE '%Loureiro' AND AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR;

/* Ex 11 #6 */
SELECT NOME
FROM AUTORES
WHERE CODIGO_AUTOR NOT IN (
    SELECT AUTORES.CODIGO_AUTOR
    FROM LIVROS, AUTORES
    WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR);

/* Ex 12 #21 */
SELECT NOME
FROM AUTORES
WHERE NOME NOT IN (
    SELECT DISTINCT NOME
    FROM AUTORES, LIVROS
    WHERE AUTORES.CODIGO_AUTOR = LIVROS.CODIGO_AUTOR AND TO_CHAR(DATA_EDICAO, 'yyyy') = TO_CHAR(SYSDATE, 'yyyy'));

/* Ex 13 #1 */
-- 19
SELECT COUNT(*) AS "Total de Livros"
FROM LIVROS;

-- 21
SELECT COUNT(*) AS "Autores"
FROM AUTORES;

-- 10
SELECT COUNT(*) AS "Clientes"
FROM CLIENTES;

/* Ex 14 #1 */
-- 11
SELECT COUNT(*) AS "Total de livros Informática"
FROM LIVROS
WHERE GENERO = 'Informática';

/* Ex 15 #1 */
-- 19 -- 32.11 -- 923331
SELECT COUNT(*) AS "Total de Livros", ROUND(AVG(PRECO_TABELA), 2) AS "Preço Médio", SUM(UNIDADES_VENDIDAS) AS "Total de Livros Vendidos"
FROM LIVROS;

/* Ex 16 #1 */
-- 22 -- 71 -- 32.5
SELECT MIN(PRECO_TABELA) AS "Preço mais baixo", MAX(PRECO_TABELA) AS "Preço mais alto", ROUND(AVG(PRECO_TABELA), 2) AS "Preço médio"
FROM LIVROS, EDITORAS
WHERE LIVROS.CODIGO_EDITORA = EDITORAS.CODIGO_EDITORA AND EDITORAS.NOME = 'FCA - EDITORA';

/* Ex 17 #7 */
SELECT LIVROS.TITULO AS "Titulo", MIN(VENDAS.PRECO_UNITARIO) AS "Preço mais baixo", MAX(VENDAS.PRECO_UNITARIO) AS "Preço mais Alto", ROUND(AVG(VENDAS.PRECO_UNITARIO), 2) AS "Preço médio"
FROM LIVROS, VENDAS
WHERE LIVROS.GENERO = 'Informática' AND LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO
GROUP BY LIVROS.TITULO;

/* Ex 18 #4 */
SELECT LIVROS.GENERO AS "Genero", MAX(LIVROS.PRECO_TABELA) - MIN(LIVROS.PRECO_TABELA) AS "Diferença"
FROM LIVROS
GROUP BY LIVROS.GENERO
ORDER BY LIVROS.GENERO ASC;

/* Ex 19 #7 */
SELECT LIVROS.TITULO, LIVROS.PRECO_TABELA AS "Preço Tabela", SUM(VENDAS.QUANTIDADE) AS "Unidades Vendidas",
LIVROS.PRECO_TABELA * SUM(VENDAS.QUANTIDADE) AS "Receita esperada", SUM(VENDAS.PRECO_UNITARIO) * SUM(VENDAS.QUANTIDADE) AS "Receita efetiva"
FROM LIVROS, VENDAS
WHERE LIVROS.CODIGO_LIVRO = VENDAS.CODIGO_LIVRO
GROUP BY LIVROS.TITULO, LIVROS.PRECO_TABELA;

/* Ex 20 #4 */
SELECT LIVROS.GENERO AS "Genero", COUNT(*) AS "Quantidade"
FROM LIVROS
GROUP BY LIVROS.GENERO
ORDER BY LIVROS.GENERO ASC;

/* Ex 21 #4 */
SELECT LIVROS.GENERO AS "Genero", COUNT(*) AS "Quantidade"
FROM LIVROS, AUTORES
WHERE LIVROS.CODIGO_AUTOR = AUTORES.CODIGO_AUTOR AND (AUTORES.NOME LIKE '%a%' OR AUTORES.MORADA LIKE '%Coimbra')
GROUP BY LIVROS.GENERO
ORDER BY LIVROS.GENERO ASC;
