/*
*
*   Ficha 5
*   TPSI
*   Pedro dos Santos Alves
*
*/

/*
*
*   1 de Junho de 2018
*
*/

/* Ex 1 */
DROP TABLE "AUTORES2";

CREATE TABLE "AUTORES2" (
    "CODIGO_AUTOR" NUMBER(4, 0) PRIMARY KEY,
    "NOME" VARCHAR2(30) NOT NULL,
    "N_CONTRIBUINTE" NUMBER(9, 0) NOT NULL,
    "MORADA" VARCHAR(50) NULL,
    "IDADE" NUMBER(4, 0) CHECK((IDADE >= 0) AND (IDADE < 200)) NULL,
    "SEXO" CHAR(1) NULL,
    "NACIONALIDADE" VARCHAR2(20) NULL,
    "GENERO_PREFERIDO" VARCHAR2(20) NULL
);

/* Ex 2 */
DROP TABLE "AVALIACOES";

CREATE TABLE "AVALIACOES" (
    "CODIGO_LIVRO" NUMBER(4),
    "CODIGO_CLIENTE" NUMBER(4),
    "NOTA" NUMBER(1) CHECK(NOTA >= 1 AND NOTA <= 5),
    CONSTRAINT "PK_AVALIACOES" PRIMARY KEY(CODIGO_LIVRO, CODIGO_CLIENTE),
    CONSTRAINT "FK_COD_LIV" FOREIGN KEY(CODIGO_LIVRO) REFERENCES LIVROS(CODIGO_LIVRO),
    CONSTRAINT "FK_COD_CL" FOREIGN KEY(CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO_CLIENTE)
);

/* Ex 3 */
DROP TABLE "LIVROS_BACKUP";

CREATE TABLE "LIVROS_BACKUP" AS (
    SELECT *
    FROM LIVROS
);

DESC LIVROS;
DESC LIVROS_BACKUP;

/* Ex 4 */
ALTER TABLE LIVROS_BACKUP
    ADD FOREIGN KEY(CODIGO_EDITORA) REFERENCES EDITORAS(CODIGO_EDITORA)
    ADD FOREIGN KEY(CODIGO_AUTOR) REFERENCES AUTORES(CODIGO_AUTOR)
;

/* Ex 5 */
INSERT INTO LIVROS_BACKUP(CODIGO_AUTOR, TITULO, DATA_EDICAO, CODIGO_EDITORA, PRECO_TABELA, PAGINAS, ISBN, CODIGO_LIVRO, UNIDADES_VENDIDAS, GENERO)
VALUES ((SELECT CODIGO_AUTOR FROM AUTORES WHERE NOME = 'Sérgio Sousa'), 'Informática para todos', SYSDATE, (SELECT CODIGO_EDITORA FROM EDITORAS WHERE NOME LIKE 'FCA%'), 24, 430, 132434, 51, 0, 'Informática');

/* Ex 6 */
DELETE FROM AUTORES2
WHERE CODIGO_AUTOR = 45;

INSERT INTO AUTORES2(NOME, CODIGO_AUTOR, N_CONTRIBUINTE)
VALUES('José de Magalhães', 45, 77665544);

/* Ex 7 */
DELETE FROM LIVROS_BACKUP
WHERE CODIGO_LIVRO = 51;

/* Ex 8 */
UPDATE LIVROS_BACKUP
SET PRECO_TABELA = (PRECO_TABELA*1.1)
WHERE GENERO = 'Aventura';

/* Ex 9 */
SELECT ROUND(AVG(PRECO_TABELA), 2)
FROM LIVROS_BACKUP
WHERE GENERO = 'Informática';

DELETE FROM LIVROS_BACKUP
WHERE GENERO = 'Informática' AND PRECO_TABELA < (
    SELECT ROUND(AVG(PRECO_TABELA), 2)
    FROM LIVROS_BACKUP
    WHERE GENERO = 'Informática');

/* Ex 10 */
DROP TABLE "VENDAS_BACKUP";

CREATE TABLE "VENDAS_BACKUP" AS (
    SELECT *
    FROM VENDAS
);

/* Ex 11 */
UPDATE VENDAS_BACKUP
SET TOTAL_VENDA = (PRECO_UNITARIO * QUANTIDADE);

/* Ex 12 */
DELETE FROM VENDAS_BACKUP
WHERE TO_CHAR(DATA_VENDA, 'MM') = 1;

/* Ex 13 */
DROP TABLE "VENDAS_BACKUP";

/* Ex 14 */
ALTER TABLE AUTORES2
    DROP COLUMN NLIVROS;

ALTER TABLE AUTORES2
    ADD (
    NLIVROS NUMBER DEFAULT 0 CHECK(NLIVROS >= 0 AND NLIVROS <= 150) NOT NULL
    );

/* Ex 15 */
DROP TABLE EDITORAS_BACKUP;

CREATE TABLE EDITORAS_BACKUP AS
    SELECT *
    FROM EDITORAS
    WHERE 1 = 0;

/* Ex 16 */
DROP SEQUENCE SEQ_EDITBACK;

-- incrementa de 1 em 1 por defeito
CREATE SEQUENCE SEQ_EDITBACK
START WITH 4;

/* Ex 17 */
INSERT INTO EDITORAS_BACKUP
VALUES (SEQ_EDITBACK.NEXTVAL, 'D.Quixote', 901111111, 'Rua Cidade de Córdova, n.2 2610-038 Alfragide', 707252252, 707252253);

INSERT INTO EDITORAS_BACKUP
VALUES (SEQ_EDITBACK.NEXTVAL, 'Almedina', 901212121, 'Rua Fernandes Tomás, n.º76 a 80 3000-167 Coimbra', 239851903, 239851904);

/* Ex 18 */
SELECT SEQ_EDITBACK.CURRVAL AS ValorAtual
FROM DUAL;

SELECT SEQ_EDITBACK.NEXTVAL AS Seguinte
FROM DUAL;

/* Ex 19 */
DROP SEQUENCE SEQ_EDITBACK;
